apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tyrannosaurus-go 
  janus-idp.io/tekton: tyrannosaurus-go
  backstage.io/kubernetes-id: tyrannosaurus-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tyrannosaurus-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  